### ISSUE TITLE
Missing steps for installation?

### ISSUE THREAD

**Issue by RyanMacG** [mathsaey/advent_of_code_utils#6]
I'm following the steps for installation and have included my session cookie in `config/config.exs` but when I run `mix aoc`

I get
```
> mix aoc
** (CompileError) config/config.exs:1: undefined function config/2 (there is no such import)
    (elixir 1.14.2) lib/code.ex:425: Code.validated_eval_string/3
    (elixir 1.14.2) lib/config.ex:288: Config.__eval__!/3
    (mix 1.14.2) lib/mix/tasks/loadconfig.ex:54: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.14.2) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
```

Should there be anything else included as part of the config?

**Comment by RyanMacG** [comment]
Ah, very helpful thanks. That's resolved the issue
